# Introduction {#ch1}

\noindent
Wild Pacific salmon _Oncorhynchus_ spp. represent a fantastic natural resource, which results largely from their unique life history strategy. Pacific salmon exhibit a migratory strategy known as anadromy: adults spawn in freshwater where eggs hatch and juveniles rear for 0, 1, or 2 years. Juveniles then migrate to the ocean where they spend the majority of their lives feeding on abundant prey resources. Once reaching maturity, adults return to their natal streams to spawn and complete the life cycle. The result of this life history strategy is an incredibly productive resource that grows entirely on its own and all but delivers itself to harvesters when the time comes for exploitation. 

There is a long history of salmon fishery resource development, exploitation, regulation, and dependence throughout Alaska [@cooley-1963]. In many cases, the resource use is dictated by the locality of the system; for example, stocks located near urban areas are often primarily exploited by recreational fishers whereas more remote stocks often constitute commercial and/or subsistence uses. This dissertation discusses the challenges and explores quantitative tools for assessing and informing management of more remote stocks and the fisheries that rely heavily upon them, with particular relevance to the remote areas of western Alaska.

Similar to all exploited natural resources, the management of Pacific salmon fisheries involves making decisions about how to exploit the resource in order to best attain a suite of biological, social, and economic objectives [@walters-1986]. These decisions are inherently difficult due to conflicting objectives and uncertainties in system state, system response to management actions, and implementation [@walters-holling-1990]. Put another way, assuming a manager knows exactly what they wish to obtain, getting there is made difficult by not knowing (for example) how large the harvestable surplus is, how the stock will respond to harvesting, or that their management action will actually result in the expected outcome. Despite these difficulties, a decision must be made [without decision-making there is no management; @hilborn-walters-1992] and the consequences, whether favorable or undesirable, must be accepted. Thus, it could be argued that the science of monitoring, assessment, and prediction in the context of Pacific salmon fisheries is tasked with informing the relative likelihood of different outcomes conditional on a candidate management action. 

The management of Pacific salmon fisheries can be thought of as a hierarchy of (1) guiding objectives, (2) management strategies to attain objectives, and (3) tactics to implement the management strategies (Table \@ref(tab:mgmt-hierarchy-table)). At the upper level, long-term decisions are made about the objectives of resource exploitation. These long-term objectives are often referred to as fundamental objectives: they are desired endpoints, but do not at all imply how they should be attained. Fundamental objectives often involve notions of sustainability and maintenance of biological diversity and often include social objectives such as maximization and stability of harvest or profit. Already, it is clear that these fundamental objectives are often conflicting. For example, consider the objective of maximizing harvest: in fisheries that harvest multiple stocks (_i_._e_., distinct spawning units), oftentimes maximum harvest may only obtained by overexploiting weak stock components and possibly eroding diversity. As another example, consider the objective of long-term sustainability: in order to ensure that the stock is sustained, some level of harvest fluctuations must be accepted (lower harvests must be allowed when the stock is at low abundance). These conflicting objectives imply that trade-offs exist -- all objectives cannot be maximized simultaneously. It is worth noting here that the decisions made at the uppermost level of the management hierarchy are based purely on societal values and salmon stock assessment scientists should play little or no advisory or advocacy roles in making many of these decisions, except to the extent that they are also members of society [@walters-martell-2004]. The Policy for the Management of Sustainable Salmon Fisheries^[5 AAC 39.222; a piece of legislation that defines correct salmon management practices by the Alaska Department of Fish and Game. Available at: http://www.adfg.alaska.gov/static/regulations/regprocess/fisheriesboard/pdfs/2016-2017/jointcommittee/5aac39.pdf] states that the objectives of salmon management in Alaska are 

> "...to ensure conservation of salmon and salmon’s required marine and aquatic habitats, protection of customary and traditional subsistence uses and other uses, and the sustained economic health of Alaska’s fishing communities." 

\noindent
The policy goes on to say that managers should target "...to the extent possible, maximum sustained yield [MSY]."

The second level of the management hierarchy is made up of harvest strategies and policies that guide how the long term objectives are to be obtained. The State of Alaska has selected the fixed escapement policy as the management strategy to obtain the long-term objectives of sustainability and yields that are close to the maximum. These escapement goals are given as ranges that dictate the target number of spawning adults each year; any portion of the stock above the escapement goal is considered surplus (excess biological production) and should be harvested for the benefit of society. Uncertainty at this intermediate level of the management hierarchy (_e_._g_., regarding the optimal escapement goal) is often a result of incomplete understanding of system status and function. For example, in order to determine what the optimal escapement goal should be to obtain MSY, knowledge of stock productivity and carrying capacity are required. These quantities are often derived using spawner-recruit analyses [see @walters-martell-2004, Ch.7 for an overview], which are inherently uncertain: data are rarely informative about the shape of the true underlying population dynamics relationships [@walters-hilborn-1976], but instead provide snapshot in time (_e_._g_., 20+ years) of how the population has responded to its environment and harvesting, and are often fraught with measurement errors [@ludwig-walters-1981]. Traditionally, it has been thought that these uncertainties can be reduced by more monitoring and the development of rigorous assessment and prediction models to better understand system function. However, it has often been argued that while monitoring and assessment models are obviously important (performance relative to objectives must be measured after all), true understanding of system behavior comes only from experimentation in management [the concept of "active adaptive management"; @walters-1986]. A classic example is to assess the maximum productivity of the stock (_i_._e_., in the absence of density dependent mortality), the spawning stock must be forced to small sizes and the resulting distribution of recruitments must be observed [@walters-hilborn-1976]. However, management actions that ensure these observations are made may be undesirable to many managers and stakeholders, considering that exploiting a stock down to these low levels is risky [@walters-1986].

At the lowest level in the management hierarchy, intra-annual (or in-season) decisions are made regarding how to exploit the current year's run according to the rules of the strategy defined in the intermediate decision level. In other words, given a management strategy (_i_._e_., fixed escapement), the manager is still tasked with deciding how to best implement the fishery within a year to ensure the strategy is followed. Salmon runs are notoriously short in duration (_e_._g_., 80% of the the run may pass in a two or three week period), necessitating swift decision-making. As is illustrated in this dissertation, these decisions at the intra-annual level of the management hierarchy are often poorly informed by data which can result in indecisiveness, subjectivity, non-transparency, frustration, and missed opportunities.

This dissertation is partitioned into three primary projects (presented in Chapters \@ref(ch2), \@ref(ch3), and \@ref(ch4)), each which expands on the aforementioned difficulties in decision-making and develops and implements quantitative tools intended to help guide managers of Pacific salmon fisheries. Each chapter relies on the Kuskokwim River drainage in western Alaska as a case study, which is characterized by being a large drainage (>50,000 km^2^), harvests are taken by primarily subsistence users who are nearly all native Alaskans, and the primary species of interest being Chinook salmon _O. tshawytscha_. This system supports one of the largest subsistence fisheries for Pacific salmon in the world in terms of the total numbers of fish harvested annually. Between 1995 and 2015, the average number of salmon harvested of all species for subsistence purposes in the Kuskokwim drainage was 201,000 (range: 140,000 -- 294,000) making up an average of 21% (range: 16 -- 28%) of all state-wide subsistence salmon harvests [data reported in annual reports, most recently in @fall-etal-2018]. The Kuskokwim River contains the largest subsistence fishery for Chinook salmon in the state: an average of 65,000 Chinook salmon were harvested in this region between 1995 and 2015 (range 15,000 -- 104,000), composing 48% (range: 34 -- 61%) of state-wide subsistence harvests for this species annually [@fall-etal-2018]. Although this dissertation is relatively narrow in its geographical and biological focus, the concepts and tools discussed, developed, and evaluated have broad generality and will be of interest to practitioners in other systems with similar spatial structures, exploitation characteristics, and/or population dynamics.

Chapter \@ref(ch2) works at the in-season level of the hierarchy to develop and evaluate the performance of a run timing forecast model that can be used to aid in the interpretation of in-season data. It includes an illustration of why uncertainty in run timing makes the interpretation of in-season abundance data difficult and a review of what is known about mechanisms driving variability of Pacific salmon run timing. The overall objective of Chapter \@ref(ch2) is to develop and evaluate the reliability of a run timing forecast model for Kuskokwim River Chinook salmon. A secondary goal of Chapter \@ref(ch2) is to retrospectively assess the utility of having access to the run timing forecast model in terms of reducing uncertainty and bias in run size indices used for in-season harvest management decisions.

Chapter \@ref(ch3) again addresses the lowest level of the management hierarchy (_i_._e_., intra-annual decision-making), but in this case in a more direct sense using an analysis framework known broadly as management strategy evaluation [MSE; _e_._g_., @butterworth-2007; @punt-etal-2014]. This analysis evaluates a set of harvest control decision rules to identify strategies that perform well at attaining pre-defined objectives (_e_._g_., meeting the escapement goal, distributing harvest equally across villages and substock components, _etc_.) across a range of biological states (_e_._g_., run size, stock composition, and run timing). The strategies assessed in this chapter fall along a continuum of complexity in their decision rules and the resulting increase in information requirements. While the fixed escapement policy seems simple to execute, actually doing so is made difficult largely due to uncertainty regarding the size of the incoming run. The MSE framework allows testing different rules for decision-making with sparse information, and may elucidate those that are robust to uncertainty. Additionally, there may be a set of decision rules that perform well at limiting harvest in low run size years but by doing so in a "fair way", where the burdens of shortages are not carried primarily by any particular subset of resource users, nor are the harvest burdens borne by a select subset of the substocks spawning within the larger drainage. If a consistent set of rules or triggers could be identified that perform reasonably well at meeting management objectives without precise knowledge of run size or harvestable surplus, it could prove useful to managers and decision-making within the region.

Chapter \@ref(ch4) moves up the hierarchy to the second level and attempts to extend the single stock assessment models currently used in many systems in Alaska to multi-stock assessments. When an aggregate stock is made up of several distinct components, each with their own productivity, it is likely that exploitation at some level (_e_._g_., 50% annually) results in the more productive components being under-exploited while the weaker stocks may be over-exploited. This reality implies a trade-off: to preserve stock diversity, some harvest must be foregone. Before the shape and magnitude of these types of "harvest-biodiversity" trade-offs can be quantified, some understanding of the variation in substock productivity and carrying capacity is required. The multi-stock assessment framework developed in Chapter \@ref(ch4) is tailored to provide this information for these sorts of trade-off analyses and others that require similar information sources. Multi-stock assessments may assume one of several different model structures (_e_._g_., by fitting separate models to the data from each stock or by fitting a single model to all data simultaneously). In some cases, one approach may be preferable over the other, and a primary objective of Chapter \@ref(ch4) is to evaluate the estimation performance of a range of assessment strategies.

\newpage

```{r mgmt-hierarchy-table}
tab = data.frame(
  ex = c("Ensure sustainability", "Maximize harvest", "Stabilize harvest", "Maximize economic value",
         "Constant escapement", "Constant exploitation rate", "Constant catch", "Adaptive exploitation",
         "Triggers and thresholds", "Time, area, gear restrictions", "Limited participation"),
  
  src = c("Relative importance of objectives", "Problem boundaries", " ", " ",
          "Stock productivity", "Stock status", "Drivers of stock change", "Shape/magnitude of trade-offs",
          "Harvestable surplus", "Uninformative data", "Fisher behavior")
)

colnames(tab) = c("\\textbf{Examples}", "\\textbf{Sources of Uncertainty}")
knitr::kable(tab, "latex", booktabs = T,
             caption = "One way of viewing the structure of renewable natural resource (including salmon) management as described in the text, including examples of alternatives and sources of uncertainty at each level.", escape = F) %>%
  kable_styling() %>%
  group_rows("Fundamental Objectives", 1,4, hline_after = T) %>%
  group_rows("Inter-annual Strategies", 5, 8, hline_after = T) %>%
  group_rows("Intra-annual Tactics", 9, 11, hline_after = T)
```
