# Appendix A {-#appendix-a}

\noindent
This appendix contains the necessary code to perform two of the main parts of the run timing forecast model approach in Chapter \@ref(ch2).

## Forecast Cross-Validation {-}

#### Function Name {-}

`forecast.CV`

#### Purpose {-}

#### Arguments {-}

\noindent
\textbf{Arguments:}

1. `x`: a vector containing the time series of the x-variable
2.  `y`: a vector containing the time series of the y-variable
3.  `start.ind`: the index to start the forecast cross-validation (e.g., 10 would train to 10 years and start forecasting in the $11^{\text{th}}$, then continue until present).
4.  `na.rm`: logical; do you wish to remove `NA` observations before calculating summary statistics?
5.  `include.last.year.in.scores`: logical; do you wish to have the last year of `y` to influence the cross-validation score?

#### Psuedocode {-}

#### Source Code {-}

\begin{singlespace}
\begin{verbatim}
forecast.CV = function(x, y, start.ind, na.rm = F, include.last.year.in.scores = T) {  
  # total number of observed pairs
  n = length(x)
  # validation end years
  val.end = start.ind:(n-1)
  n.val = length(val.end)
  # containers
  error = numeric(n.val)
  abs.error = numeric(n.val)
  pred.se = numeric(n.val)
  # containers for training data
  train.x = list()
  train.y = list()
  # containers for validation data
  val.x = numeric(n.val)
  val.y = numeric(n.val)
  pred.val.y = numeric(n.val)
  for (i in 1:n.val) {
    # indices to train and validate over
    train.ind = 1:val.end[i]
    val.ind = max(train.ind) + 1
    # store the training data
    train.x[[i]] = x[train.ind]
    train.y[[i]] = y[train.ind]
    # store the validation data
    val.x[i] = x[val.ind]
    val.y[i] = y[val.ind]
    # fit model to training data
    temp.x = train.x[[i]]; temp.y = train.y[[i]]
    fit = lm(temp.y ~ temp.x)
    sig = summary(fit)$sigma
    # forecast
    pred.val.y[i] = predict(fit, newdata = data.frame(temp.x = val.x[i]))
    # statistics
    error[i] = val.y[i] - pred.val.y[i]
    abs.error[i] = abs(error[i])
  }
  
  if (!include.last.year.in.scores) {
    error[n.val] = NA
    abs.error[n.val] = NA
  } 
  
  # return output
  output = list(error = error, abs.error = abs.error, mae = mean(abs.error, na.rm = na.rm))
  return(output)
}
\end{verbatim}
\end{singlespace}

## Sliding Climate-Window {-}

<!-- This makes space between the citations -->
<!--  \setlength{\hangindent}{0.7cm} -->
<!--  \hangindent=2em -->
<!--  \hangafter=1 -->
\setlength{\parskip}{6pt plus 2pt minus 1pt}
